<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder {
    /**
    * Run the database seeds.
    */

    public function run(): void {
        $products = [
            // Fiction ( Category 1 )
            [
                'name' => '1984',
                'slug' => Str::slug( '1984' ),
                'short_description' => 'A dystopian novel set in a totalitarian society.',
                'description' => '1984 by George Orwell depicts a society under constant surveillance, ruled by a totalitarian regime led by Big Brother.',
                'regular_price' => 299000,
                'sale_price' => null,
                'SKU' => '1984-001',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 100,
                'image' => null,
                'images' => null,
                'category_id' => 1,
                'author_id' => 1,
            ],
            [
                'name' => 'Animal Farm',
                'slug' => Str::slug( 'Animal Farm' ),
                'short_description' => 'A satirical allegory of Soviet totalitarianism.',
                'description' => 'Animal Farm by George Orwell is a novella about farm animals who rebel against their human farmer, hoping to create a society where animals can be equal.',
                'regular_price' => 249000,
                'sale_price' => 199000,
                'SKU' => 'ANIMAL-002',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 120,
                'image' => null,
                'images' => null,
                'category_id' => 1,
                'author_id' => 1,
            ],

            // Non-Fiction ( Category 2 )
            [
                'name' => 'Outliers',
                'slug' => Str::slug( 'Outliers' ),
                'short_description' => 'An exploration of the factors that contribute to high levels of success.',
                'description' => 'Outliers by Malcolm Gladwell delves into what makes people successful, examining the hidden advantages and opportunities.',
                'regular_price' => 359000,
                'sale_price' => null,
                'SKU' => 'OUTL-003',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 80,
                'image' => null,
                'images' => null,
                'category_id' => 2,
                'author_id' => 2,
            ],
            [
                'name' => 'The Tipping Point',
                'slug' => Str::slug( 'The Tipping Point' ),
                'short_description' => 'How little things can make a big difference.',
                'description' => 'The Tipping Point by Malcolm Gladwell explores how ideas, products, messages, and behaviors spread like viruses.',
                'regular_price' => 339000,
                'sale_price' => 289000,
                'SKU' => 'TIPP-004',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 95,
                'image' => null,
                'images' => null,
                'category_id' => 2,
                'author_id' => 2,
            ],

            // Mystery ( Category 3 )
            [
                'name' => 'Murder on the Orient Express',
                'slug' => Str::slug( 'Murder on the Orient Express' ),
                'short_description' => 'A famous detective story by Agatha Christie.',
                'description' => 'Murder on the Orient Express by Agatha Christie features Hercule Poirot solving a murder on a luxury train.',
                'regular_price' => 229000,
                'sale_price' => null,
                'SKU' => 'MURD-005',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 120,
                'image' => null,
                'images' => null,
                'category_id' => 3,
                'author_id' => 3,
            ],
            [
                'name' => 'And Then There Were None',
                'slug' => Str::slug( 'And Then There Were None' ),
                'short_description' => 'Ten strangers are invited to an isolated island.',
                'description' => 'And Then There Were None by Agatha Christie is a mystery where ten people are lured to an island and murdered one by one.',
                'regular_price' => 269000,
                'sale_price' => null,
                'SKU' => 'THEN-006',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 110,
                'image' => null,
                'images' => null,
                'category_id' => 3,
                'author_id' => 3,
            ],
            [
                'name' => 'Death on the Nile',
                'slug' => Str::slug( 'Death on the Nile' ),
                'short_description' => 'A murder mystery set on a luxury cruise.',
                'description' => 'Death on the Nile by Agatha Christie follows Hercule Poirot as he investigates a murder aboard a Nile river cruise.',
                'regular_price' => 249000,
                'sale_price' => 199000,
                'SKU' => 'NILE-007',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 85,
                'image' => null,
                'images' => null,
                'category_id' => 3,
                'author_id' => 3,
            ],

            // Thriller ( Category 4 )
            [
                'name' => 'Gone Girl',
                'slug' => Str::slug( 'Gone Girl' ),
                'short_description' => 'A psychological thriller about a missing wife.',
                'description' => 'Gone Girl by Gillian Flynn is a psychological thriller that explores the secrets between a married couple.',
                'regular_price' => 339000,
                'sale_price' => null,
                'SKU' => 'GONE-008',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 60,
                'image' => null,
                'images' => null,
                'category_id' => 4,
                'author_id' => 4,
            ],
            [
                'name' => 'Sharp Objects',
                'slug' => Str::slug( 'Sharp Objects' ),
                'short_description' => 'A journalist returns to her hometown to cover murders.',
                'description' => 'Sharp Objects by Gillian Flynn follows a reporter who must confront her past while investigating a series of murders.',
                'regular_price' => 319000,
                'sale_price' => null,
                'SKU' => 'SHARP-009',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 75,
                'image' => null,
                'images' => null,
                'category_id' => 4,
                'author_id' => 4,
            ],

            // Romance ( Category 5 )
            [
                'name' => 'The Wedding',
                'slug' => Str::slug( 'The Wedding' ),
                'short_description' => 'A love story with twists and turns.',
                'description' => 'The Wedding by Nora Roberts follows a couple through challenges and triumphs in their relationship.',
                'regular_price' => 269000,
                'sale_price' => null,
                'SKU' => 'WEDD-010',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 100,
                'image' => null,
                'images' => null,
                'category_id' => 5,
                'author_id' => 5,
            ],
            [
                'name' => 'Vision in White',
                'slug' => Str::slug( 'Vision in White' ),
                'short_description' => 'A wedding photographer finds unexpected love.',
                'description' => 'Vision in White by Nora Roberts is the first book in the Bride Quartet series about four friends who run a wedding planning business.',
                'regular_price' => 299000,
                'sale_price' => 249000,
                'SKU' => 'VISION-011',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 90,
                'image' => null,
                'images' => null,
                'category_id' => 5,
                'author_id' => 5,
            ],
            [
                'name' => 'Blue Dahlia',
                'slug' => Str::slug( 'Blue Dahlia' ),
                'short_description' => 'Romance blooms at a garden center.',
                'description' => 'Blue Dahlia by Nora Roberts tells the story of a widow who starts a new life and finds love at a garden center.',
                'regular_price' => 269000,
                'sale_price' => null,
                'SKU' => 'BLUE-012',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 105,
                'image' => null,
                'images' => null,
                'category_id' => 5,
                'author_id' => 5,
            ],

            // Science Fiction ( Category 6 )
            [
                'name' => 'I, Robot',
                'slug' => Str::slug( 'I, Robot' ),
                'short_description' => 'A collection of science fiction stories.',
                'description' => 'I, Robot by Isaac Asimov is a collection of stories that set the foundation for modern robotics.',
                'regular_price' => 319000,
                'sale_price' => null,
                'SKU' => 'IROB-013',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 85,
                'image' => null,
                'images' => null,
                'category_id' => 6,
                'author_id' => 6,
            ],
            [
                'name' => 'Foundation',
                'slug' => Str::slug( 'Foundation' ),
                'short_description' => 'The epic saga of the Foundation.',
                'description' => 'Foundation by Isaac Asimov is the first novel in the Foundation series, exploring the fall of a galactic empire.',
                'regular_price' => 339000,
                'sale_price' => 289000,
                'SKU' => 'FOUND-014',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 130,
                'image' => null,
                'images' => null,
                'category_id' => 6,
                'author_id' => 6,
            ],
            [
                'name' => 'The Gods Themselves',
                'slug' => Str::slug( 'The Gods Themselves' ),
                'short_description' => 'A tale of parallel universes and energy.',
                'description' => 'The Gods Themselves by Isaac Asimov explores the consequences of energy transfer between parallel universes.',
                'regular_price' => 319000,
                'sale_price' => null,
                'SKU' => 'GODS-015',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 70,
                'image' => null,
                'images' => null,
                'category_id' => 6,
                'author_id' => 6,
            ],

            // Fantasy ( Category 7 )
            [
                'name' => 'The Hobbit',
                'slug' => Str::slug( 'The Hobbit' ),
                'short_description' => 'A fantasy novel by J.R.R. Tolkien.',
                'description' => 'The Hobbit by J.R.R. Tolkien is a high-fantasy novel that follows Bilbo Baggins on his journey to reclaim a treasure.',
                'regular_price' => 289000,
                'sale_price' => null,
                'SKU' => 'HOBBIT-016',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 130,
                'image' => null,
                'images' => null,
                'category_id' => 7,
                'author_id' => 7,
            ],
            [
                'name' => 'The Lord of the Rings',
                'slug' => Str::slug( 'The Lord of the Rings' ),
                'short_description' => 'The epic fantasy trilogy.',
                'description' => 'The Lord of the Rings by J.R.R. Tolkien is an epic fantasy trilogy following the quest to destroy the One Ring.',
                'regular_price' => 699000,
                'sale_price' => 579000,
                'SKU' => 'LOTR-017',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 200,
                'image' => null,
                'images' => null,
                'category_id' => 7,
                'author_id' => 7,
            ],
            [
                'name' => 'The Silmarillion',
                'slug' => Str::slug( 'The Silmarillion' ),
                'short_description' => 'The mythological history of Middle-earth.',
                'description' => 'The Silmarillion by J.R.R. Tolkien chronicles the creation of Middle-earth and the events of the First Age.',
                'regular_price' => 389000,
                'sale_price' => null,
                'SKU' => 'SILM-018',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 65,
                'image' => null,
                'images' => null,
                'category_id' => 7,
                'author_id' => 7,
            ],

            // Historical Fiction ( Category 8 )
            [
                'name' => 'The Pillars of the Earth',
                'slug' => Str::slug( 'The Pillars of the Earth' ),
                'short_description' => 'An epic tale of cathedral building in medieval England.',
                'description' => 'The Pillars of the Earth by Ken Follett follows the building of a cathedral in 12th-century England amid political intrigue.',
                'regular_price' => 439000,
                'sale_price' => null,
                'SKU' => 'PILL-019',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 140,
                'image' => null,
                'images' => null,
                'category_id' => 8,
                'author_id' => 8,
            ],
            [
                'name' => 'World Without End',
                'slug' => Str::slug( 'World Without End' ),
                'short_description' => 'The sequel to The Pillars of the Earth.',
                'description' => 'World Without End by Ken Follett continues the story of Kingsbridge two centuries later during the Black Death.',
                'regular_price' => 459000,
                'sale_price' => 389000,
                'SKU' => 'WORLD-020',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 115,
                'image' => null,
                'images' => null,
                'category_id' => 8,
                'author_id' => 8,
            ],

            // Biography ( Category 9 )
            [
                'name' => 'Steve Jobs',
                'slug' => Str::slug( 'Steve Jobs Biography' ),
                'short_description' => 'The authorized biography of Steve Jobs.',
                'description' => 'Steve Jobs by Walter Isaacson is the definitive biography of the Apple co-founder, based on exclusive interviews.',
                'regular_price' => 419000,
                'sale_price' => null,
                'SKU' => 'JOBS-021',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 125,
                'image' => null,
                'images' => null,
                'category_id' => 9,
                'author_id' => 9,
            ],

            // Memoir ( Category 10 )
            [
                'name' => 'Becoming',
                'slug' => Str::slug( 'Becoming' ),
                'short_description' => 'The intimate memoir of Michelle Obama.',
                'description' => 'Becoming by Michelle Obama chronicles her journey from the South Side of Chicago to the White House.',
                'regular_price' => 389000,
                'sale_price' => 339000,
                'SKU' => 'BECOM-022',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 180,
                'image' => null,
                'images' => null,
                'category_id' => 10,
                'author_id' => 10,
            ],

            // Self-Help ( Category 11 )
            [
                'name' => 'How to Win Friends and Influence People',
                'slug' => Str::slug( 'How to Win Friends and Influence People' ),
                'short_description' => 'The classic guide to interpersonal relations.',
                'description' => 'How to Win Friends and Influence People by Dale Carnegie offers timeless advice on building relationships and influencing others.',
                'regular_price' => 299000,
                'sale_price' => null,
                'SKU' => 'FRIEN-023',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 150,
                'image' => null,
                'images' => null,
                'category_id' => 11,
                'author_id' => 11,
            ],
            [
                'name' => 'How to Stop Worrying and Start Living',
                'slug' => Str::slug( 'How to Stop Worrying and Start Living' ),
                'short_description' => 'Techniques to conquer worry and lead a fulfilling life.',
                'description' => 'How to Stop Worrying and Start Living by Dale Carnegie provides practical methods to reduce stress and anxiety.',
                'regular_price' => 269000,
                'sale_price' => 229000,
                'SKU' => 'WORRY-024',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 95,
                'image' => null,
                'images' => null,
                'category_id' => 11,
                'author_id' => 11,
            ],

            // Health & Wellness ( Category 12 )
            [
                'name' => 'The Seven Spiritual Laws of Success',
                'slug' => Str::slug( 'The Seven Spiritual Laws of Success' ),
                'short_description' => 'A practical guide to fulfilling your dreams.',
                'description' => 'The Seven Spiritual Laws of Success by Deepak Chopra offers wisdom for achieving success through spiritual principles.',
                'regular_price' => 319000,
                'sale_price' => null,
                'SKU' => 'SEVEN-025',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 110,
                'image' => null,
                'images' => null,
                'category_id' => 12,
                'author_id' => 12,
            ],
            [
                'name' => 'Quantum Healing',
                'slug' => Str::slug( 'Quantum Healing' ),
                'short_description' => 'Exploring the frontiers of mind/body medicine.',
                'description' => 'Quantum Healing by Deepak Chopra examines the connection between consciousness and healing.',
                'regular_price' => 339000,
                'sale_price' => 289000,
                'SKU' => 'QUANT-026',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 80,
                'image' => null,
                'images' => null,
                'category_id' => 12,
                'author_id' => 12,
            ],

            // Science & Nature ( Category 13 )
            [
                'name' => 'The Selfish Gene',
                'slug' => Str::slug( 'The Selfish Gene' ),
                'short_description' => 'A gene-centered view of evolution.',
                'description' => 'The Selfish Gene by Richard Dawkins revolutionized our understanding of evolution and natural selection.',
                'regular_price' => 369000,
                'sale_price' => null,
                'SKU' => 'SELFI-027',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 135,
                'image' => null,
                'images' => null,
                'category_id' => 13,
                'author_id' => 13,
            ],
            [
                'name' => 'The God Delusion',
                'slug' => Str::slug( 'The God Delusion' ),
                'short_description' => 'A critique of religion and advocacy for atheism.',
                'description' => 'The God Delusion by Richard Dawkins argues against the existence of a supernatural creator.',
                'regular_price' => 389000,
                'sale_price' => 339000,
                'SKU' => 'GOD-028',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 100,
                'image' => null,
                'images' => null,
                'category_id' => 13,
                'author_id' => 13,
            ],

            // Travel ( Category 14 )
            [
                'name' => 'The Great Railway Bazaar',
                'slug' => Str::slug( 'The Great Railway Bazaar' ),
                'short_description' => 'A train journey through Asia.',
                'description' => 'The Great Railway Bazaar by Paul Theroux chronicles a four-month journey by train through Asia.',
                'regular_price' => 339000,
                'sale_price' => null,
                'SKU' => 'RAIL-029',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 75,
                'image' => null,
                'images' => null,
                'category_id' => 14,
                'author_id' => 14,
            ],
            [
                'name' => 'Dark Star Safari',
                'slug' => Str::slug( 'Dark Star Safari' ),
                'short_description' => 'Overland from Cairo to Cape Town.',
                'description' => 'Dark Star Safari by Paul Theroux is a travel memoir of a journey through Africa from north to south.',
                'regular_price' => 369000,
                'sale_price' => 319000,
                'SKU' => 'DARK-030',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 65,
                'image' => null,
                'images' => null,
                'category_id' => 14,
                'author_id' => 14,
            ],

            // Cooking ( Category 15 )
            [
                'name' => 'Mastering the Art of French Cooking',
                'slug' => Str::slug( 'Mastering the Art of French Cooking' ),
                'short_description' => 'The definitive guide to French cuisine.',
                'description' => 'Mastering the Art of French Cooking by Julia Child is the classic cookbook that brought French cuisine to American homes.',
                'regular_price' => 849000,
                'sale_price' => null,
                'SKU' => 'MAST-031',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 90,
                'image' => null,
                'images' => null,
                'category_id' => 15,
                'author_id' => 15,
            ],
            [
                'name' => 'My Life in France',
                'slug' => Str::slug( 'My Life in France' ),
                'short_description' => 'Julia Child\'s memoir of her years in France.',
                'description' => 'My Life in France by Julia Child recounts her discovery of French cuisine and the writing of her groundbreaking cookbook.',
                'regular_price' => 389000,
                'sale_price' => 339000,
                'SKU' => 'LIFE-032',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 70,
                'image' => null,
                'images' => null,
                'category_id' => 15,
                'author_id' => 15,
            ],

            // Art & Photography (Category 16)
            [
                'name' => 'Ansel Adams: 400 Photographs',
                'slug' => Str::slug('Ansel Adams 400 Photographs'),
                'short_description' => 'A comprehensive collection of iconic images.',
                'description' => 'Ansel Adams: 400 Photographs showcases the master photographer\'s most stunning landscape work.',
                'regular_price' => 1089000,
                'sale_price' => null,
                'SKU' => 'ANSEL-033',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 55,
                'image' => null,
                'images' => null,
                'category_id' => 16,
                'author_id' => 16,
            ],
            [
                'name' => 'The Camera',
                'slug' => Str::slug( 'The Camera' ),
                'short_description' => 'Ansel Adams\' guide to photographic technique.',
                'description' => 'The Camera by Ansel Adams is a technical guide to camera operation and photographic principles.',
                'regular_price' => 699000,
                'sale_price' => 579000,
                'SKU' => 'CAM-034',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 60,
                'image' => null,
                'images' => null,
                'category_id' => 16,
                'author_id' => 16,
            ],

            // Children's Books ( Category 17 )
                [
                    'name' => 'Charlie and the Chocolate Factory',
                    'slug' => Str::slug( 'Charlie and the Chocolate Factory' ),
                    'short_description' => 'A magical adventure in a chocolate factory.',
                    'description' => 'Charlie and the Chocolate Factory by Roald Dahl tells the story of a poor boy who wins a tour of a mysterious chocolate factory.',
                    'regular_price' => 209000,
                    'sale_price' => null,
                    'SKU' => 'CHAR-035',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 200,
                    'image' => null,
                    'images' => null,
                    'category_id' => 17,
                    'author_id' => 17,
                ],
                [
                    'name' => 'Matilda',
                    'slug' => Str::slug( 'Matilda' ),
                    'short_description' => 'A brilliant girl with magical powers.',
                    'description' => 'Matilda by Roald Dahl is about an extraordinary girl who uses her intelligence and telekinetic powers to overcome adversity.',
                    'regular_price' => 209000,
                    'sale_price' => 159000,
                    'SKU' => 'MAT-036',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 175,
                    'image' => null,
                    'images' => null,
                    'category_id' => 17,
                    'author_id' => 17,
                ],
                [
                    'name' => 'James and the Giant Peach',
                    'slug' => Str::slug( 'James and the Giant Peach' ),
                    'short_description' => 'A fantastical journey inside a giant peach.',
                    'description' => 'James and the Giant Peach by Roald Dahl follows a young orphan on a magical adventure with insect friends.',
                    'regular_price' => 189000,
                    'sale_price' => null,
                    'SKU' => 'JAMES-037',
                    'stock_status' => 'instock',
                    'featured' => 0,
                    'quantity' => 140,
                    'image' => null,
                    'images' => null,
                    'category_id' => 17,
                    'author_id' => 17,
                ],

                // Young Adult ( Category 18 )
                [
                    'name' => 'The Fault in Our Stars',
                    'slug' => Str::slug( 'The Fault in Our Stars' ),
                    'short_description' => 'A touching love story between two cancer patients.',
                    'description' => 'The Fault in Our Stars by John Green is a poignant novel about two teenagers who meet at a cancer support group.',
                    'regular_price' => 299000,
                    'sale_price' => null,
                    'SKU' => 'FAULT-038',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 160,
                    'image' => null,
                    'images' => null,
                    'category_id' => 18,
                    'author_id' => 18,
                ],
                [
                    'name' => 'Looking for Alaska',
                    'slug' => Str::slug( 'Looking for Alaska' ),
                    'short_description' => 'A coming-of-age story at boarding school.',
                    'description' => 'Looking for Alaska by John Green follows a teenager at boarding school as he searches for meaning after a tragedy.',
                    'regular_price' => 269000,
                    'sale_price' => 229000,
                    'SKU' => 'ALASKA-039',
                    'stock_status' => 'instock',
                    'featured' => 0,
                    'quantity' => 125,
                    'image' => null,
                    'images' => null,
                    'category_id' => 18,
                    'author_id' => 18,
                ],
                [
                    'name' => 'Paper Towns',
                    'slug' => Str::slug( 'Paper Towns' ),
                    'short_description' => 'A mystery about finding a missing girl.',
                    'description' => 'Paper Towns by John Green follows a boy on a road trip to find the girl who mysteriously disappeared.',
                    'regular_price' => 269000,
                    'sale_price' => null,
                    'SKU' => 'PAPER-040',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 145,
                    'image' => null,
                    'images' => null,
                    'category_id' => 18,
                    'author_id' => 18,
                ],

                // Poetry ( Category 19 )
                [
                    'name' => 'Milk and Honey',
                    'slug' => Str::slug( 'Milk and Honey' ),
                    'short_description' => 'A collection of poetry about survival and healing.',
                    'description' => 'Milk and Honey by Rupi Kaur is a collection of poetry divided into four chapters dealing with different themes of pain and healing.',
                    'regular_price' => 339000,
                    'sale_price' => null,
                    'SKU' => 'MILK-041',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 190,
                    'image' => null,
                    'images' => null,
                    'category_id' => 19,
                    'author_id' => 19,
                ],
                [
                    'name' => 'The Sun and Her Flowers',
                    'slug' => Str::slug( 'The Sun and Her Flowers' ),
                    'short_description' => 'Poetry about growth, healing, and femininity.',
                    'description' => 'The Sun and Her Flowers by Rupi Kaur explores themes of wilting, falling, rooting, rising, and blooming.',
                    'regular_price' => 389000,
                    'sale_price' => 339000,
                    'SKU' => 'SUN-042',
                    'stock_status' => 'instock',
                    'featured' => 0,
                    'quantity' => 165,
                    'image' => null,
                    'images' => null,
                    'category_id' => 19,
                    'author_id' => 19,
                ],

                // Religion & Spirituality ( Category 20 )
                [
                    'name' => 'The Power of Now',
                    'slug' => Str::slug( 'The Power of Now' ),
                    'short_description' => 'A guide to spiritual enlightenment.',
                    'description' => 'The Power of Now by Eckhart Tolle shows readers how to live in the present moment and achieve inner peace.',
                    'regular_price' => 369000,
                    'sale_price' => null,
                    'SKU' => 'POWER-043',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 155,
                    'image' => null,
                    'images' => null,
                    'category_id' => 20,
                    'author_id' => 20,
                ],
                [
                    'name' => 'A New Earth',
                    'slug' => Str::slug( 'A New Earth' ),
                    'short_description' => 'Awakening to your life\'s purpose.',
                'description' => 'A New Earth by Eckhart Tolle illuminates how transcending ego-based consciousness leads to a new way of being.',
                'regular_price' => 389000,
                'sale_price' => 319000,
                'SKU' => 'EARTH-044',
                'stock_status' => 'instock',
                'featured' => 0,
                'quantity' => 130,
                'image' => null,
                'images' => null,
                'category_id' => 20,
                'author_id' => 20,
            ],

            // Business & Finance (Category 21)
            [
                'name' => 'The Essays of Warren Buffett',
                'slug' => Str::slug('The Essays of Warren Buffett'),
                'short_description' => 'Lessons for corporate America.',
                'description' => 'The Essays of Warren Buffett compiles the investment wisdom and business principles of the legendary investor.',
                'regular_price' => 579000,
                'sale_price' => null,
                'SKU' => 'BUFF-045',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 105,
                'image' => null,
                'images' => null,
                'category_id' => 21,
                'author_id' => 21,
            ],

            // Education & Teaching (Category 22)
            [
                'name' => 'The Element',
                'slug' => Str::slug('The Element'),
                'short_description' => 'How finding your passion changes everything.',
                'description' => 'The Element by Ken Robinson explores how discovering one\'s natural talents leads to fulfillment and success.',
                    'regular_price' => 339000,
                    'sale_price' => null,
                    'SKU' => 'ELEM-046',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 115,
                    'image' => null,
                    'images' => null,
                    'category_id' => 22,
                    'author_id' => 22,
                ],
                [
                    'name' => 'Creative Schools',
                    'slug' => Str::slug( 'Creative Schools' ),
                    'short_description' => 'The grassroots revolution transforming education.',
                    'description' => 'Creative Schools by Ken Robinson argues for an education system that nurtures creativity and individual talents.',
                    'regular_price' => 369000,
                    'sale_price' => 289000,
                    'SKU' => 'CREAT-047',
                    'stock_status' => 'instock',
                    'featured' => 0,
                    'quantity' => 95,
                    'image' => null,
                    'images' => null,
                    'category_id' => 22,
                    'author_id' => 22,
                ],

                // Comics & Graphic Novels ( Category 23 )
                [
                    'name' => 'Watchmen',
                    'slug' => Str::slug( 'Watchmen' ),
                    'short_description' => 'A groundbreaking graphic novel about superheroes.',
                    'description' => 'Watchmen by Alan Moore is a dark, complex graphic novel that deconstructs the superhero genre.',
                    'regular_price' => 459000,
                    'sale_price' => null,
                    'SKU' => 'WATCH-048',
                    'stock_status' => 'instock',
                    'featured' => 1,
                    'quantity' => 140,
                    'image' => null,
                    'images' => null,
                    'category_id' => 23,
                    'author_id' => 23,
                ],
                [
                    'name' => 'V for Vendetta',
                    'slug' => Str::slug( 'V for Vendetta' ),
                    'short_description' => 'A dystopian tale of freedom and anarchy.',
                    'description' => 'V for Vendetta by Alan Moore tells the story of a masked vigilante fighting against a totalitarian government.',
                    'regular_price' => 419000,
                    'sale_price' => 369000,
                    'SKU' => 'VEND-049',
                    'stock_status' => 'instock',
                    'featured' => 0,
                    'quantity' => 110,
                    'image' => null,
                    'images' => null,
                    'category_id' => 23,
                    'author_id' => 23,
                ],

                // Technology ( Category 24 )
                [
                    'name' => 'The Facebook Effect',
                    'slug' => Str::slug( 'The Facebook Effect' ),
                    'short_description' => 'The inside story of the company connecting the world.',
                    'description' => 'The Facebook Effect chronicles the rise of Facebook and Mark Zuckerberg\'s vision for social networking.',
                'regular_price' => 389000,
                'sale_price' => null,
                'SKU' => 'FACE-050',
                'stock_status' => 'instock',
                'featured' => 1,
                'quantity' => 85,
                'image' => null,
                'images' => null,
                'category_id' => 24,
                'author_id' => 24,
            ],
        ];

        DB::table('products' )->insert( $products );
                }
            }
