[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'nodejs_18', 'mysql80', 'nginx', 'gettext']

[phases.install]
cmds = [
    'npm install',
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && bash start.sh'
