[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
