[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "php artisan config:clear && php artisan migrate:refresh --seed --force && php artisan config:cache --no-interaction && php artisan route:cache --no-interaction && php artisan view:cache --no-interaction && php artisan embeddings:generate && bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
